### PR TITLE
Change connection id syntax

### PR DESCRIPTION
**Pull request by topher515**

### CODE REVIEW

**Comment by cannoneyed** [comment]
@topher515 looks reasonable, maybe we need 5 colons? - just to make ingestion into neo4j easier?

**Comment by cannoneyed** [comment]
The other thing we could do that might be better anyway would be to actually create some information about the connection in the `connection` object, a la

``` javascript
{
  'facebook:129124328882::::facebook:1287917237123': {
    lat: 37.41,
    lng: -122.4,
    timestamp: 39213892381
    shared: facebook:129124328882,
    received: facebook:1287917237123,
  }
}
```

Probably gonna want to keep track of who's doing the sharing pretty soon

**Comment by topher515** [comment]
yeah thats the information I actually need—To be able to differentiate between the shared and received in that list.

I've setup a new project at https://github.com/topher515/tmm-glare-graph which is a pure node service which watches for changes in connections and adds them into the neo4j database. next will be to make queries from the db like "show me the route which connects _this_ user to _the m machine_ main user (or something like that)"

**Comment by cannoneyed** [comment]
Rad. Welp feel free to submit a PR for adding that connection data as well... I'll make an issue for it and see if I can get to it once I'm done getting the player and notification system working swimmingly

**Pull request merged**
